apiVersion: v1
kind: PersistentVolume
metadata:
  name: geth-data-pv
spec:
  capacity:
    storage: 500Gi  # Ethereum chain data is large, adjust as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/ethereum/geth
    type: DirectoryOrCreate