apiVersion: v1
kind: Service
metadata:
  name: geth
spec:
  selector:
    app: geth
  ports:
  - name: http-rpc
    port: 8545
    targetPort: 8545
  - name: ws-rpc
    port: 8546
    targetPort: 8546
  - name: p2p-tcp
    port: 30303
    targetPort: 30303
    protocol: TCP
  - name: p2p-udp
    port: 30303
    targetPort: 30303
    protocol: UDP
  - name: engine-api
    port: 8551
    targetPort: 8551
  - name: metrics
    port: 6060
    targetPort: 6060