---
# Common system setup tasks

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install basic system packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - python3-pip
      - ntpdate
      - chrony
      - fail2ban
      - htop
      - iotop
      - sysstat
    state: present

- name: Set timezone to {{ system_timezone }}
  timezone:
    name: "{{ system_timezone }}"

- name: Ensure chrony service is running for time synchronization
  service:
    name: chrony
    state: started
    enabled: yes

- name: Set system limits for Ethereum node
  pam_limits:
    domain: "*"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items:
    - { limit_type: soft, limit_item: nofile, value: "{{ open_file_limit }}" }
    - { limit_type: hard, limit_item: nofile, value: "{{ open_file_limit }}" }
    - { limit_type: soft, limit_item: nproc, value: "65535" }
    - { limit_type: hard, limit_item: nproc, value: "65535" }

- name: Tune kernel parameters for Ethereum node
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
    reload: yes
  with_items:
    - { name: net.core.somaxconn, value: "65535" }
    - { name: net.core.netdev_max_backlog, value: "65536" }
    - { name: net.ipv4.tcp_max_syn_backlog, value: "65536" }
    - { name: net.ipv4.tcp_slow_start_after_idle, value: "0" }
    - { name: net.ipv4.tcp_tw_reuse, value: "1" }
    - { name: net.ipv4.ip_local_port_range, value: "1024 65535" }
    - { name: vm.max_map_count, value: "262144" }
    - { name: vm.swappiness, value: "{{ swappiness }}" }