apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: local-storage
  volumeName: geth-data-pv