apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lighthouse-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: local-storage
  volumeName: lighthouse-data-pv