apiVersion: v1
kind: PersistentVolume
metadata:
  name: lighthouse-data-pv
spec:
  capacity:
    storage: 200Gi  # Adjust based on your needs
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/ethereum/lighthouse
    type: DirectoryOrCreate