apiVersion: v1
kind: Service
metadata:
  name: lighthouse
spec:
  selector:
    app: lighthouse
  ports:
  - name: p2p-tcp
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: p2p-udp
    port: 9000
    targetPort: 9000
    protocol: UDP
  - name: http-api
    port: 5052
    targetPort: 5052
  - name: metrics
    port: 5054
    targetPort: 5054