apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lighthouse
spec:
  serviceName: "lighthouse"
  replicas: 1
  selector:
    matchLabels:
      app: lighthouse
  template:
    metadata:
      labels:
        app: lighthouse
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 1000
      containers:
      - name: lighthouse
        image: sigp/lighthouse:latest
        command: ["lighthouse"]
        args:
          - "beacon_node"
          - "--datadir=/data"
          - "--network=sepolia"
          - "--execution-endpoint=http://geth:8551"
          - "--execution-jwt=/secrets/jwt/jwt.hex"
          - "--allow-insecure-genesis-sync"
          - "--http"
          - "--http-address=0.0.0.0"
          - "--metrics"
          - "--metrics-address=0.0.0.0"
        ports:
        - containerPort: 9000
          name: p2p-tcp
        - containerPort: 9000
          protocol: UDP
          name: p2p-udp
        - containerPort: 5052
          name: http-api
        - containerPort: 5054
          name: metrics
        volumeMounts:
        - name: data
          mountPath: /data
        - name: jwt-secret
          mountPath: /secrets/jwt
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: lighthouse-data-pvc
      - name: jwt-secret
        configMap:
          name: jwt-secret