---
# ConfigMap for Geth
apiVersion: v1
kind: ConfigMap
metadata:
  name: geth-config
  namespace: ethereum-node
data:
  geth-config.toml: |
    [Eth]
    SyncMode = "snap"

    [Node]
    DataDir = "/data"
    HTTPHost = "0.0.0.0"
    HTTPPort = 8545
    HTTPVirtualHosts = ["*"]
    HTTPModules = ["eth", "net", "web3", "txpool"]

    [Node.P2P]
    MaxPeers = 50
    NoDiscovery = false

    [Metrics]
    HTTP = "0.0.0.0"
    Port = 6060
    Enabled = true
---
# ConfigMap for Lighthouse
apiVersion: v1
kind: ConfigMap
metadata:
  name: lighthouse-config
  namespace: ethereum-node
data:
  lighthouse-config.sh: |
    #!/bin/sh
    exec lighthouse \
      --network mainnet \
      --datadir /data \
      --http \
      --http-address 0.0.0.0 \
      --http-port 5052 \
      --metrics \
      --metrics-address 0.0.0.0 \
      --metrics-port 5054 \
      --execution-endpoint http://geth-service:8551 \
      --execution-jwt /secrets/jwt/jwtsecret \
      beacon
---
# ConfigMap for Prometheus
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ethereum-node
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'geth'
        static_configs:
          - targets: ['geth-service:6060']

      - job_name: 'lighthouse'
        static_configs:
          - targets: ['lighthouse-service:5054']

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name