apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lighthouse
  namespace: ethereum-node
spec:
  serviceName: "lighthouse"
  replicas: 1
  selector:
    matchLabels:
      app: lighthouse
  template:
    metadata:
      labels:
        app: lighthouse
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5054"
    spec:
      terminationGracePeriodSeconds: 300
      securityContext:
        fsGroup: 2000  # Set group ID for volume access
      containers:
      - name: lighthouse
        image: sigp/lighthouse:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["/config/lighthouse-config.sh"]
        ports:
        - containerPort: 5052
          name: http
        - containerPort: 5054
          name: metrics
        - containerPort: 9000
          name: p2p-tcp
          protocol: TCP
        - containerPort: 9000
          name: p2p-udp
          protocol: UDP
        volumeMounts:
        - name: lighthouse-data
          mountPath: /data
        - name: config
          mountPath: /config
        - name: jwt-secret
          mountPath: /secrets/jwt
          readOnly: true
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        livenessProbe:
          httpGet:
            path: /lighthouse/health
            port: 5052
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /lighthouse/health
            port: 5052
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: config
        configMap:
          name: lighthouse-config
          defaultMode: 0755  # Make script executable
      - name: jwt-secret
        secret:
          secretName: jwt-secret
      - name: lighthouse-data
        persistentVolumeClaim:
          claimName: lighthouse-data-pvc