---
apiVersion: v1
kind: Service
metadata:
  name: geth-node
  labels:
    {{- include "ethereum-node.labels" . | nindent 4 }}
    component: geth
spec:
  selector:
    app: geth
  ports:
  - name: http-rpc
    port: 8545
    targetPort: 8545
  - name: ws-rpc
    port: 8546
    targetPort: 8546
  - name: p2p-tcp
    port: 30303
    targetPort: 30303
    protocol: TCP
  - name: p2p-udp
    port: 30303
    targetPort: 30303
    protocol: UDP
  - name: engine-api
    port: 8551
    targetPort: 8551
  - name: metrics
    port: 6060
    targetPort: 6060
---
apiVersion: v1
kind: Service
metadata:
  name: lighthouse
  labels:
    app: lighthouse
    {{- include "ethereum-node.labels" . | nindent 4 }}
spec:
  selector:
    app: lighthouse
  ports:
  - name: p2p-tcp
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: p2p-udp
    port: 9000
    targetPort: 9000
    protocol: UDP
  - name: http-api
    port: 5052
    targetPort: 5052
  - name: metrics
    port: 5054
    targetPort: 5054