apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ethereum-node.fullname" . }}-lighthouse
  namespace: monitoring
  labels:
    {{- include "ethereum-node.labels" . | nindent 4 }}
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: lighthouse
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s