apiVersion: v2
name: ethereum-node
description: A Helm chart for Ethereum execution and consensus clients on Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: prometheus
    version: ~19.0.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: ~6.50.0
    repository: https://grafana.github.io/helm-charts